export const dummyProperties = [
  {
    id: "1",
    title: "Modern Luxury Apartment",
    location: "Manhattan, New York",
    price: 2500,
    type: "Apartment",
    status: "rent",
    bedrooms: 4,
    bathrooms: 3,
    area: 2200,
    featured: true,
    image: "/images/image1.webp",
    description:
      "A stunning luxury apartment with modern interiors, spacious rooms, and breathtaking city skyline views.",
  },
  {
    id: "2",
    title: "Contemporary Beachfront Villa",
    location: "Miami, Florida",
    price: 850000,
    type: "Villa",
    status: "sale",
    bedrooms: 5,
    bathrooms: 4,
    area: 4500,
    featured: true,
    image: "/images/image2.webp",
    description:
      "An exclusive oceanfront villa featuring a private infinity pool, direct beach access, and floor-to-ceiling windows.",
  },
  {
    id: "3",
    title: "Minimalist City Penthouse",
    location: "Downtown, Chicago",
    price: 4200,
    type: "Penthouse",
    status: "rent",
    bedrooms: 3,
    bathrooms: 2,
    area: 1850,
    featured: false,
    image: "/images/image3.webp",
    description:
      "A sleek urban penthouse equipped with smart home automation, open-plan living, and a private rooftop terrace.",
  },
  {
    id: "4",
    title: "Cozy Suburb Family Home",
    location: "Austin, Texas",
    price: 480000,
    type: "House",
    status: "sale",
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    featured: false,
    image: "/images/image4.webp",
    description:
      "A charming family house located in a quiet neighborhood with a spacious backyard, modern kitchen, and solar panels.",
  },
  {
    id: "5",
    title: "Rustic Mountain Cabin",
    location: "Aspen, Colorado",
    price: 650000,
    type: "Cabin",
    status: "sale",
    bedrooms: 3,
    bathrooms: 2,
    area: 1950,
    featured: true,
    image: "/images/image5.webp",
    description:
      "A peaceful mountain retreat featuring exposed wood beams, a stone fireplace, and panoramic alpine views.",
  },
  {
    id: "6",
    title: "Elegant Waterfront Townhouse",
    location: "Seattle, Washington",
    price: 3800,
    type: "Townhouse",
    status: "rent",
    bedrooms: 3,
    bathrooms: 3,
    area: 2100,
    featured: false,
    image: "/images/image6.webp",
    description:
      "A stylish multi-level townhouse near the harbor with private garage parking, a balcony, and top-tier amenities.",
  },
  {
    id: "7",
    title: "Sunset Boulevard Studio",
    location: "Los Angeles, California",
    price: 1900,
    type: "Studio",
    status: "rent",
    bedrooms: 1,
    bathrooms: 1,
    area: 850,
    featured: false,
    image: "/images/image7.webp",
    description:
      "A compact yet stylish studio apartment in the heart of Hollywood, perfect for young professionals and creatives.",
  },
];
